resolve label field
SeedCompany/cord-api-v3 pull request #1154
Opened 2020-09-09 18:31 UTC by tjgersho

2020-09-09 22:54 UTC, CarsonF requested changes
We want to shorten the label in certain cases. Look at the examples a few lines above this.

2020-09-10 04:38 UTC, tjgersho commented
For example, 
Matthew 1-John 2 means Matthew 1:1-John 2:`end verse number`. Right?

2020-09-10 06:43 UTC, CarsonF commented
Exactly :+1:

2020-09-10 17:09 UTC, tjgersho commented
- Matthew 1:1-John 3:21 should be Matthew 1-John 3:21
- Matthew 1:1-John last:last should be Matthew-John
- Matthew 1:1-Matthew 2:4 should be Matthew 1-2:4

The cases above are right?

2020-09-10 21:10 UTC, CarsonF commented
> * Matthew 2:1-John 3:21 should be Matthew 2-John 3:21

If we are displaying verses on one side in which they aren't the first/last verse, let's display them on both. "Matthew 2:1-John 3:21"

If it was "Matthew 1:1-John 3:last" then that would become "Matthew 1-John 2"
If it was "Matthew 1:1-Matthew 3:last" then that would become "Matthew 1-3"


> * Matthew 1:1-John last:last should be Matthew-John

👍 

> * Matthew 1:1-Matthew 2:4 should be Matthew 1-2:4

Same for this as first case. Matthew 1:1-2:4

2020-09-11 15:58 UTC, CarsonF reviewed
Looks good @tjgersho. Could you just make this one change?

2020-09-11 15:58 UTC, CarsonF commented on src/components/scripture/scripture-range.resolver.ts
>    label(@Parent() _range: ScriptureRange): string {
```suggestion
  label(@Parent() { start, end }: ScriptureRange): string {
```

2020-09-11 16:26 UTC, CarsonF approved these changes

2020-09-11 16:26 UTC, merged