Add registry of geography module
SeedCompany/cord-api-v3 pull request #1249
Opened 2020-09-21 17:36 UTC by zkhin

2020-09-21 20:50 UTC, michaelmarshall commented on src/components/registry-of-geography/registry-of-geography.service.ts
> +  async delete(id: string, session: ISession): Promise<void> {
deletes are being refacored. this can be skipped for now. we won't use ACLs in the future.

2020-09-21 20:50 UTC, michaelmarshall commented on test/registry-of-geography.e2e-spec.ts
> +  it('delete registry of geography', async () => {
this can be skipped for now.

2020-09-21 21:34 UTC, CarsonF requested changes
"Registry" is a list, and we aren't creating a list of lists. We need to identify these objects by a noun representing their singular item.

> The function of the Registry of Geography (ROG) is to document standardized codes for geopolitical areas.
https://hisregistries.org/rog/

_GeopoliticalArea_ might be a solution.

I also can't figure out what HIS is actually doing here. It looks like they just say that GENC is the standard, ....or basically ISO 3166 codes?...

This [CountryCodeCrossReference.pdf](https://hisregistries.org/wp-content/uploads/filebase/rog/CountryCodeCrossReference.pdf) seems to define a bunch of fields.
We should probably have another discussion on what we need to support here.

2020-09-21 21:42 UTC, zkhin commented
I guess we would use the ISO2 or the two letter country codes from here https://www.cia.gov/library/publications/the-world-factbook/appendix/appendix-d.html#

2020-09-28 23:08 UTC, CarsonF commented
Ok after talking with everyone we decided that Location can just store an ISO 3166-3 code instead of referencing/manually managing this legacy standard. 😁 

Thanks for the effort @zkhin 😞

2020-09-28 23:08 UTC, closed without merging