Add/remove/lists other locations in project
SeedCompany/cord-api-v3 pull request #1369
Opened 2020-10-15 20:43 UTC by zkhin

2020-10-21 23:27 UTC, michaelmarshall approved these changes

2020-10-22 17:21 UTC, CarsonF requested changes

2020-10-22 17:21 UTC, CarsonF commented on src/components/project/project.resolver.ts
> +    @Args('locationId', { type: () => ID }) locationId: string
Can you do the args thing here too?

2020-10-22 17:21 UTC, CarsonF commented on src/components/project/project.service.ts
> +    );
Why not use `calculateTotalAndPaginateList`?

2020-10-22 19:08 UTC, CarsonF approved these changes

2020-10-22 19:08 UTC, CarsonF commented on src/components/project/project.service.ts
> +      await this.removeOtherLocation(projectId, locationId, session);
Still don't like this, but we can come back to it.

2020-10-22 19:09 UTC, merged