Add location fields to User and Organization modules
SeedCompany/cord-api-v3 pull request #1379
Opened 2020-10-19 12:53 UTC by zkhin

2020-10-21 17:28 UTC, CarsonF requested changes

2020-10-21 17:28 UTC, CarsonF commented on src/components/organization/organization.resolver.ts
> +    @Args('locationId', { type: () => ID }) locationId: string
Could you do these like:
https://github.com/SeedCompany/cord-api-v3/blob/229348e2c1d577051ba770a49560e7c37c8a7997/src/components/authorization/authorization.resolver.ts#L34
https://github.com/SeedCompany/cord-api-v3/blob/229348e2c1d577051ba770a49560e7c37c8a7997/src/components/authorization/authorization.resolver.ts#L13-L16
That way IDs are validated.

2020-10-21 23:31 UTC, michaelmarshall submitted a review, later dismissed

2020-10-21 23:56 UTC, CarsonF commented on src/components/user/user.service.ts
> +      await this.removeLocation(userId, locationId, session);
There's gotta be a better way to do this.

2020-10-22 22:41 UTC, CarsonF approved these changes

2020-10-22 22:43 UTC, CarsonF commented
We've got list/add/remove locations on several resources. It could be better to abstract this in `LocationService` as just pass in the piece of the query define the relationship to the location.

2020-10-22 23:07 UTC, zkhin commented
> We've got list/add/remove locations on several resources. It could be better to abstract this in `LocationService` as just pass in the piece of the query define the relationship to the location.

Okay, I will create a new ticket/PR for refactoring for this

2020-10-22 23:08 UTC, merged