#1408 no duplicate partners
SeedCompany/cord-api-v3 pull request #1431
Opened 2020-10-23 16:20 UTC by elisabeth-sorrell

2020-10-23 17:23 UTC, CarsonF requested changes

2020-10-23 17:23 UTC, CarsonF commented on src/components/partner/partner.service.ts
> +        'organization.id',
The field should match the input object
```suggestion
        'partner.organizationId',
```

2020-10-23 19:47 UTC, elisabeth-sorrell commented
@CarsonF done

2020-10-26 16:40 UTC, CarsonF approved these changes

2020-10-26 16:52 UTC, merged