#633 add logic to be able to sort on special characters.
SeedCompany/cord-api-v3 pull request #1456
Opened 2020-10-29 19:32 UTC by elisabeth-sorrell

2020-10-29 19:35 UTC, elisabeth-sorrell commented
@CarsonF could you take a quick look at this solution?... the latest of master hasn't been merged in, but I just wanted to see what you thought of the solution.

2020-11-03 00:27 UTC, CarsonF requested changes
Thinking about it more and after a brief discussion with Michael.

I think there's just not a problem with having a `sortValue` on every property node. For the majority of the cases it could be the same value as value, but for strings we could deburr it. 
```ts
const nodeProps = {
  createdAt,
  value,
  sortValue: determineSortValue(value),
};

const determineSortValue = (value: unknown) =>
  typeof value === 'string' ? deburr(value) : value;
```

----

Another option would be to only have `sortValue` when necessary. 

In that case we could just do:
```ts
const determineSortValue = (value: unknown) =>
  typeof value === 'string' ? deburr(value) : undefined;
```
Returning `undefined` should just omit it from the db.

We'd need the sorting logic to be smarter then, to know whether to sort on `sortValue` or `value`.

2020-11-03 00:27 UTC, CarsonF commented on src/core/database/results/parse-base-node.ts
> +  return { id, createdAt, sortValue };
We shouldn't ever need to pull the sortValue out of the database. It will only be used in queries.

2020-11-03 00:27 UTC, CarsonF commented on src/core/database/database.service.ts
> +    if (await this.hasSortValue({ session, object, key, nodevar })) {
We should be able to use the same logic as we do on create to determine the sort value. We shouldn't need to pull the current value out of the database to determine this.

2020-11-10 19:24 UTC, elisabeth-sorrell commented
@CarsonF ready for review

2020-11-10 21:48 UTC, michaelmarshall approved these changes

2020-11-12 16:39 UTC, elisabeth-sorrell commented
@michaelmarshall rebased on master

2020-11-12 20:59 UTC, michaelmarshall approved these changes

2020-11-12 20:59 UTC, merged