Procedure roles to java roles
SeedCompany/cord-api-v3 pull request #1649
Opened 2021-02-18 03:12 UTC by elisabeth-sorrell

Admin, consultant-manager, consultant, controller, field-operations-director completed. 
Went through admin role at least twice.

One weird discrepancy:
Java Procedure code has a `partners` property, and the API code has a `knownLanguage` property. Checked the user service, and looks like partners is handled by the partner service, and looks like knownLanguage is part of the user object. I'm assuming theses changes were made in API, but the updated not reflected in the Java code, but not sure.

2021-02-18 18:53 UTC, CarsonF requested changes

2021-02-18 18:53 UTC, CarsonF commented on src/common/resource.dto.ts
> -  readonly canDelete: boolean;
This needs to be reverted. The UI uses this to determine if the resource can be deleted or not.

2021-02-18 18:53 UTC, CarsonF commented on src/components/budget/dto/budget-record.dto.ts
> +  readonly canDelete: SecuredBoolean;
canDelete is not a secured boolean. The boolean represents whether the requesting user can delete the resource or not. It doesn't make sense for the user to not be able to read it and there's nothing to edit there.

I'm assuming this is just trying to sync between java. I'd suggest dropping all the canDelete changes and additions as we haven't really worked out how they will work and they are not the same as properties.

2021-02-19 01:39 UTC, michaelmarshall commented
closing. replaced by #1656

2021-02-19 01:39 UTC, closed without merging