Allow administrator to assign roles
SeedCompany/cord-api-v3 pull request #2028
Opened 2021-07-15 19:55 UTC by tmpacifitech

https://github.com/SeedCompany/cord-field/issues/722

2021-07-15 21:02 UTC, CarsonF requested changes

2021-07-15 21:02 UTC, CarsonF commented on src/components/project/project-member/project-member.service.ts
> +      !session.roles.includes('global:Administrator')
Move this check to the if statement above so we don't call User.readOne when we don't need to.

2021-07-15 21:36 UTC, CarsonF commented on src/components/project/project-member/project-member.service.ts
> +      !session.roles.includes('global:Administrator')
Nevermind. This isn't needed. See comment on UI PR.

There may need to be some changes to the role files to limit who can change User.roles.

2021-07-18 19:08 UTC, tmpacifitech commented
@CarsonF Seems like `DbUser.roles` permission is configured properly in roles files and we can close this PR.

2021-07-19 12:18 UTC, closed without merging