Periodic Reports | Skipped Boolean & Reason
SeedCompany/cord-api-v3 pull request #2170
Opened 2021-09-27 15:32 UTC by daniel-leod

Closes #1998

2021-09-27 23:36 UTC, CarsonF requested changes
- [ ] Please add a migration to add these two new props to all existing reports. See [AddPresetInventory](https://github.com/SeedCompany/cord-api-v3/blob/narrative-report-form/src/components/project/migrations/AddPresetInventory.migration.ts) as an example.
- [ ] Secure them

@sethmcknight Should skipped reason be required when skipped is being set to true?

2021-09-27 23:36 UTC, CarsonF commented on src/components/periodic-report/dto/periodic-report.dto.ts
> +  readonly skippedReason?: string;
These should be secured, and unfortunately that means right now that all the role files need to be updated to allow these two new props.

2021-09-28 12:52 UTC, sethmcknight commented
> * [ ]  Please add a migration to add these two new props to all existing reports. See [AddPresetInventory](https://github.com/SeedCompany/cord-api-v3/blob/narrative-report-form/src/components/project/migrations/AddPresetInventory.migration.ts) as an example.
> * [ ]  Secure them
> 
> @sethmcknight Should skipped reason be required when skipped is being set to true?

@CarsonF @daniel-leod yes, we should required a reason.

2021-09-28 15:25 UTC, CarsonF commented
Since it's required, let's just drop the `skipped` boolean. It can be easily calculated from `skippedReason != null`

2021-09-28 17:20 UTC, CarsonF requested changes
Needs migration still too

2021-09-28 17:20 UTC, CarsonF commented on src/components/periodic-report/periodic-report.repository.ts
> +      skipped: input.skippedReason != null,
Err sorry I mean that in general. We don't have to write this to the DB as we can check it on read.

2021-09-28 22:20 UTC, CarsonF approved these changes
Thanks @daniel-leod!

2021-09-28 22:20 UTC, merged