Allow field region and primary location to be null when updated
SeedCompany/cord-api-v3 pull request #2208
Opened 2021-10-12 21:15 UTC by daniel-leod

Fixes #2206

2021-10-14 20:43 UTC, elisabeth-sorrell requested changes
I tried running your branch and updating with an empty region and location, but nothing seemed to happen.....?

2021-10-14 22:06 UTC, elisabeth-sorrell commented
> @elisabeth-sorrell I'm going to check right now. Are you updating those fields through the UI? If so please use run this [branch ](https://github.com/SeedCompany/cord-field/pull/959)too

Yes, I had tried with the UI, but not with this branch. Trying that now

2021-10-15 01:13 UTC, elisabeth-sorrell approved these changes

2021-11-11 23:00 UTC, CarsonF approved these changes
I flattened the double if statements, merged the db query methods, and re-apply the check that `limit 1` clause was doing previously.

2021-11-12 00:35 UTC, merged