Restrict pointOfContact read/write permissions for consultant manager, financial analyst, marketing and staff member roles
SeedCompany/cord-api-v3 pull request #2231
Opened 2021-10-22 20:27 UTC by daniel-leod

Fixes #2150

2021-11-05 18:13 UTC, bryanjnelson requested changes

2021-11-05 18:13 UTC, bryanjnelson commented on src/components/authorization/roles/marketing-global.role.ts
>          { propertyName: 'pmcEntityCode', permission: { read, }, },
Similarly here what you did so far looks good, but probably remove the read permission from `pmcEntityCode` entirely, and also take the read permission for `organization` down to Low Sensitivity to match the Sheet:

![Screen Shot 2021-11-05 at 2 07 41 PM](https://user-images.githubusercontent.com/1914742/140558115-68e1194b-b4af-4a4d-9042-0e58259bf157.png)

2021-11-05 18:13 UTC, bryanjnelson commented on src/components/authorization/roles/marketing-on-project.role.ts
>          { propertyName: 'pmcEntityCode', permission: { read, }, },
The `pointOfContact` looks good; you can do the same thing for `pmcEntityCode`.

2021-11-05 18:13 UTC, bryanjnelson commented on src/components/authorization/roles/staff-member.role.ts
>          { propertyName: 'pmcEntityCode', permission: { read, }, },
Again `pointOfContact` looks good; you can do the same with `pmcEntityCode`.  And also take `organization` down to Low Sensitivity.

2021-11-09 20:11 UTC, bryanjnelson requested changes

2021-11-09 20:21 UTC, bryanjnelson approved these changes

2021-11-09 20:22 UTC, bryanjnelson commented
@daniel-leod - Looks good!
@CarsonF - Ready for merge!

2021-11-11 22:27 UTC, CarsonF approved these changes

2021-11-11 22:29 UTC, merged