Switch relationship direction from parent FileNode to FileNode and rename from 'parent' to 'child'
SeedCompany/cord-api-v3 pull request #2425
Opened 2022-04-25 16:28 UTC by elisabeth-sorrell

Refer to https://github.com/SeedCompany/cord-api-v3/issues/1753 for more info. This help make sure all BaseNode to BaseNodes are the same relationship direction.

2022-04-25 16:55 UTC, elisabeth-sorrell commented
Closes https://github.com/SeedCompany/cord-api-v3/issues/2424

2022-04-25 17:29 UTC, CarsonF reviewed
Previously migrations should not be changed as they would be working with the old schema.

2022-04-27 13:17 UTC, CarsonF requested changes
See prev comment

2022-04-27 17:09 UTC, CarsonF commented on src/components/file/file.repository.ts
> +        relation('in', 'child', 'child', ACTIVE, '*'),
I think the query variable should continue to be called `parent` as it is one of the _parents_ of the node.
```suggestion
        relation('in', 'parent', 'child', ACTIVE, '*'),
```

2022-04-27 17:09 UTC, CarsonF commented on src/components/file/migrations/ChangeFileToFileRels.migration.ts
> +        CALL apoc.refactor.rename.type("parent", "child", rels )
Can we combine these two queries? Either one after the other or maybe both in sub queries after matching the appropriate relationships?

2022-04-27 17:09 UTC, CarsonF commented on src/components/file/migrations/ChangeFileToFileRels.migration.ts
> +      .raw(`CALL apoc.refactor.invert(rel) yield input, output`)
We also have around 500k of these relationships in prod. Any idea if either of these procedures will handle this? Or do we need to wrap them in an `apoc.periodic.iterate`?

2022-04-29 16:56 UTC, elisabeth-sorrell commented
@CarsonF back to you

2022-05-18 14:57 UTC, elisabeth-sorrell commented
@CarsonF Just making sure you know that the comments on the PR have been addressed

2024-08-15 01:54 UTC, sethmcknight commented
Too old

2024-08-15 01:54 UTC, closed without merging