Attempt to handle large product queries more gracefully.
SeedCompany/cord-api-v3 pull request #2545
Opened 2022-10-18 15:58 UTC by bryanjnelson

- Create/handle new Session Expired Error
- Lower max batch size of product lower to 25 from 100

2022-10-18 16:30 UTC, CarsonF requested changes

2022-10-18 16:30 UTC, CarsonF commented on src/components/product/product.loader.ts
> +      batchScheduleFn: (cb) => setTimeout(cb, 10),
```suggestion
      ...super.getOptions(),
```

2022-10-18 16:30 UTC, CarsonF commented on src/core/database/errors.ts
> +  static readonly code = 'ServiceUnavailable' as const;
```suggestion
  static readonly code = 'SessionExpired' as const;
```
Also need to call `fromNeo` in the `cast` function below.

2022-10-18 16:30 UTC, CarsonF commented on src/core/exception.filter.ts
> +        message: 'The CORD database session has expired',
```suggestion
        message: 'The query to the database has expired',
```
maybe this would be better?

2022-10-18 19:26 UTC, bryanjnelson commented
@CarsonF - I'll squash after your review.

2022-10-18 19:34 UTC, CarsonF reviewed
Close ;)

2022-10-18 19:34 UTC, CarsonF commented on src/core/database/errors.ts
> +  static readonly code = 'SessionExpiredError' as const;
```suggestion
  static readonly code = 'SessionExpired' as const;
```

2022-10-18 19:35 UTC, bryanjnelson commented on src/core/database/errors.ts
> +  static readonly code = 'SessionExpiredError' as const;
🤦🏼‍♂️

2022-10-18 21:06 UTC, CarsonF approved these changes
Thanks man!

2022-10-19 22:13 UTC, bryanjnelson commented
@CarsonF - it's forcing another review 😕

2022-10-19 22:21 UTC, CarsonF approved these changes

2022-10-20 11:09 UTC, merged