Alter Address from string to object.
SeedCompany/cord-api-v3 pull request #2859
Opened 2023-08-09 19:20 UTC by bryanjnelson

2023-09-26 19:12 UTC, atGit2021 commented
@bryanjnelson I squashed a lot of garbage commits in order to clean up and make the changes more readable. All the Tests pass now, but the only piece of functionality that remains outstanding is the "list" partners/organizations endpoint which doesn't seem to hydrate in any data.  I'm not sure if the issues resides inside of the loader decorator or somewhere else.  I will need your help or Carson's help to figure out why it hydrates correctly in other calls, but not in the partners/organizations list endpoint.

2023-09-26 23:46 UTC, atGit2021 commented
> @bryanjnelson I squashed a lot of garbage commits in order to clean up and make the changes more readable. All the Tests pass now, but the only piece of functionality that remains outstanding is the "list" partners/organizations endpoint which doesn't seem to hydrate in any data. I'm not sure if the issues resides inside of the loader decorator or somewhere else. I will need your help or Carson's help to figure out why it hydrates correctly in other calls, but not in the partners/organizations list endpoint.

@bryanjnelson,  I was able to get list to work.  Now it's out putting all the organizations and partners!

2023-09-27 14:01 UTC, atGit2021 commented
@bryanjnelson, I'm not able to add you as a reviewer, but just fyi, it's not ready for review.

2023-09-28 21:38 UTC, bryanjnelson commented on src/components/organization/organization.service.ts
> +    }
Might this be more concise as a ternary?

2023-09-28 21:38 UTC, bryanjnelson commented on src/components/partner/partner.service.ts
> +    }
Same as above?

2023-09-29 14:39 UTC, bryanjnelson commented
LGTM @atGit2021!  Over to you @CarsonF.

2023-10-06 22:07 UTC, CarsonF requested changes
Mostly just:
- clean up from resource -> value object stuff
- allowing address to be set to null

2023-10-06 22:07 UTC, CarsonF commented on src/components/organization/organization.service.ts
> +        };
```suggestion
    const changes = {
      ...this.repo.getActualChanges(organization, input),
      address: ifDiff(compareNullable(isAddressEqual)(input.address, organization.address),
    };
```

2023-10-06 22:07 UTC, CarsonF commented on src/components/organization/organization.service.ts
> +    if (Object.keys(orgChanges).length > 0 || 'address' in changesToVerify) {
```suggestion
```

2023-10-06 22:07 UTC, CarsonF commented on src/components/organization/organization.service.ts
> +    if (Object.keys(orgChanges).length > 0) {
```suggestion
```

2023-10-06 22:07 UTC, CarsonF commented on src/components/organization/organization.service.ts
> +    if (address && 'address' in changesToVerify) {
```suggestion
    if (changes.address !== undefined) {
```

2023-10-06 22:07 UTC, CarsonF commented on src/components/organization/organization.repository.ts
> +    addressToUpdate: MailingAddress,
```suggestion
    addressToUpdate: MailingAddress | null,
```

2023-10-16 22:58 UTC, atGit2021 commented on src/components/mailing-address/dto/mailing-address.dto.ts
moved the mailing address folder to /common

2024-08-15 01:06 UTC, sethmcknight commented
This lived to the end of its lifetime and died

2024-08-15 01:06 UTC, closed without merging