Agl/add is language of consultiung boolean
SeedCompany/cord-api-v3 pull request #2983
Opened 2023-12-06 20:27 UTC by adam-soltech

2023-12-11 19:18 UTC, bryanjnelson requested changes
Thanks @adam-soltech!

2023-12-11 19:18 UTC, bryanjnelson commented on dbschema/migrations/00033.edgeql
You wouldn't have known this, but we're not actually checking in EdgeDB Migrations at this point.  Carson is handling this himself, and grouping them together as makes sense.  Eventually that will change after we're fully migrated, but for now don't worry about doing the migration.

2023-12-11 19:28 UTC, CarsonF commented
`Language.isLanguageOfConsulting` seems not the best name since it has the object name in it again.
- `isUsedForConsulting`?
- `canBeUsedForConsulting`?
- `allowedForConsulting`?
- `consulting`?

maybe an enum list would be better to encompass all of these?
```ts
Language.allowedUse = ['WiderCommunication', 'Consulting', 'X'];
```
Though I guess it would be better to describe what this language _is_ vs how the language is allowed to be used in other places.
If we wanted different roles/conditions to be able to assign individual values, then a single list isn't the best way.

2023-12-11 20:01 UTC, adam-soltech commented on dbschema/migrations/00033.edgeql
Without the migration the [e2e tests failed](https://github.com/SeedCompany/cord-api-v3/actions/runs/7134600634/job/19429741481)

2023-12-11 21:23 UTC, bryanjnelson commented on dbschema/migrations/00033.edgeql
Ah yes.  Then for now just eliminate the EdgeDB additions completely.  We'll attack that in a separate PR altogether.

2023-12-12 21:01 UTC, adam-soltech commented on dbschema/migrations/00033.edgeql
That also breaks the build. I sent the commit without edgedb and broken build to the dev channel

2023-12-12 21:04 UTC, CarsonF commented
`isUsed` seems like the least offensive prefix. I wonder if `isUsedWithConsultants` would be better than `ForConsulting`?

2023-12-12 21:15 UTC, bryanjnelson commented
> `isUsed` seems like the least offensive prefix. I wonder if `isUsedWithConsultants` would be better than `ForConsulting`?

If the UI is going to say "for consulting" then I'd just as soon match that.  Not much is gained otherwise imo.

2023-12-12 21:48 UTC, CarsonF commented
I guess that's a question for product.

2023-12-12 22:10 UTC, adam-soltech commented
> > `isUsed` seems like the least offensive prefix. I wonder if `isUsedWithConsultants` would be better than `ForConsulting`?
> 
> If the UI is going to say "for consulting" then I'd just as soon match that. Not much is gained otherwise imo.

I agree but will run it by product in standup tomorrow

2024-01-25 20:11 UTC, bryanjnelson commented on dbschema/migrations/00033.edgeql
You'll still want to take both the .edgql and .esdl files out of this PR.  Edge stuff is being done separately.

2024-08-15 01:05 UTC, sethmcknight commented
This lived to the end of its lifetime and died

2024-08-15 01:05 UTC, closed without merging