Added marketingRegion
SeedCompany/cord-api-v3 pull request #3048
Opened 2024-01-16 22:45 UTC by willdch

https://seed-company-squad.monday.com/boards/3451697530/pulses/5186746393

2024-01-17 00:49 UTC, CarsonF requested changes
This should be a computed. It's not stored in the database or updated in a mutation. It's just a helper calculation.

```ts
Project.marketingRegion =>
	(.marketingRegionOverride ?? .marketingCountry.marketingRegion)
```

2024-01-17 15:36 UTC, atGit2021 commented
> This should be a computed. It's not stored in the database or updated in a mutation. It's just a helper calculation.
> 
> ```ts
> Project.marketingRegion =>
> 	(.marketingRegionOverride ?? .marketingCountry.marketingRegion)
> ```

@CarsonF, do you recommend that we compute the value inside of the hydrate function within the project repository?  I assume we keep the marketingRegion property in the update DTO in order to pass down the value that a user may select to override to, but do we need it in the create DTO?  Let us know what you are thinking.

2024-01-17 15:51 UTC, CarsonF commented
> do you recommend that we compute the value inside of the hydrate function within the project repository? 

That sounds like the easiest thing to do.

> I assume we keep the marketingRegion property in the update DTO in order to pass down the value that a user may select to override to, but do we need it in the create DTO?

No the create & update DTOs should not reference this property. It is computed/calculated so where would that user input save to? It doesn't make sense.

2024-01-17 15:53 UTC, CarsonF commented on src/components/project/dto/project.dto.ts
> +  readonly marketingRegion: Secured<IdOf<Location> | null>;
```suggestion
  @Calculated()
  readonly marketingRegion: Secured<IdOf<Location> | null>;
```
This let's the permission system know that edits are not applicable.

Also seen here:
https://github.com/SeedCompany/cord-api-v3/blob/e867d3f50f37fb18c670aef0cd01462b024496c4/src/components/engagement/dto/engagement.dto.ts#L96-L106

2024-01-17 15:59 UTC, atGit2021 commented
> > do you recommend that we compute the value inside of the hydrate function within the project repository?
> 
> That sounds like the easiest thing to do.
> 
> > I assume we keep the marketingRegion property in the update DTO in order to pass down the value that a user may select to override to, but do we need it in the create DTO?
> 
> No the create & update DTOs should not reference this property. It is computed/calculated so where would that user input save to? It doesn't make sense.

So when a user clicks on the new marketingRegion button in the UI and sets the value to something new, we should use the marketingRegionOverride property to pass that value down to the API and update the override property?

2024-01-17 16:00 UTC, CarsonF commented
> So when a user clicks on the new marketingRegion button in the UI and sets the value to something new, we should use the marketingRegionOverride property to pass that value down to the API and update the override property?

Correct.

2024-02-05 19:17 UTC, willdch commented
Closing in favor of [PR 3047](https://github.com/SeedCompany/cord-api-v3/pull/3047).

- After creating this branch I realized I needed to have access to the `marketingCountry` property on 3047 in order for the coalesce to work. 
- Added the same changes as a commit on 3047's PR.

2024-02-05 19:17 UTC, closed without merging