Initial draft of progress report workflow schema
SeedCompany/cord-api-v3 pull request #3080
Opened 2024-02-12 20:56 UTC by atGit2021

2024-02-13 17:47 UTC, bryanjnelson requested changes

2024-02-13 17:47 UTC, bryanjnelson commented on dbschema/project.esdl
> +
I think these make the most sense inside the Workflow Transition type.  They would then be part of module, so could be renamed and reference like `WorkflowTransition.name` & `WorkflowTransition.type`.

2024-02-13 17:47 UTC, bryanjnelson commented on dbschema/progress-report-workflow-transition.esdl
> +module default {
I think this is fine as a separate `esdl`, but I would rename to just `workflow-transition.esdl` and have it inside of the `ProgressReport` module.

2024-02-13 19:45 UTC, bryanjnelson reviewed
@CarsonF - We're sending this over your way.  I think @atGit2021 has done a great job thus far, but it is possible both of us are off on something here.  Thoughts appreciated.

2024-02-13 19:45 UTC, bryanjnelson commented on dbschema/workflow-transition.esdl
> +    `notify`: MembersWithRoles;
@CarsonF - We're a little unsure if we've represented this correctly from the application code.  Thoughts?

2024-02-13 20:03 UTC, atGit2021 commented
@CarsonF I'm not sure how to resolve the error that's causing the CI tests to fail.

2024-02-14 18:24 UTC, CarsonF requested changes

2024-02-14 18:24 UTC, CarsonF commented on dbschema/workflow-transition.esdl
I'd like to keep the workflow loose & flexible, which is why it's currently in app code. That also allows us to make changes that affect all envs (without data migration).

The only data point that's currently stored in the DB is the transition ID in the workflow event.
While that's not ideal for viewing event log without API, I think we should keep it this way at least until after migration.

2024-02-14 18:24 UTC, CarsonF commented on dbschema/progress-report.esdl
>      overloaded engagement: LanguageEngagement;
Need a `workflowEvents` multi link here.

2024-02-14 18:24 UTC, CarsonF commented on dbschema/workflow-event.esdl
> +    required notes: RichText {
```suggestion
    notes: RichText {
```

2024-02-14 18:24 UTC, CarsonF commented on dbschema/workflow-event.esdl
> +      readonly := true;
```suggestion
      readonly := true;
      default := currentUser;
```

2024-02-14 18:27 UTC, CarsonF commented on dbschema/workflow-event.esdl
> +      readonly := true;
```suggestion
      readonly := true;
      default := datetime_of_statement();
```

2024-02-27 23:18 UTC, CarsonF approved these changes

2024-02-28 15:16 UTC, merged