[EdgeDB]  OtherProduct seeds
SeedCompany/cord-api-v3 pull request #3117
Opened 2024-03-13 22:58 UTC by willdch

https://seed-company-squad.monday.com/boards/5989610236/pulses/5793006654

2024-03-14 14:49 UTC, bryanjnelson requested changes
Looks great @willdch!  Much better formatting as well!  😉

2024-03-14 14:53 UTC, bryanjnelson commented on dbschema/seeds/014.product.edgeql
> +  select { `Added Other Products` := newOtherProducts.project.name ++ ': ' ++ newOtherProducts.title }
Remove the indention on the last line here.  It should be flush on the left.  Also, we always want one new line at the end of every file.  👊🏼

2024-03-14 16:15 UTC, bryanjnelson requested changes

2024-03-14 16:15 UTC, bryanjnelson commented on dbschema/seeds/014.product.edgeql
> +    "mediums": ["Audio","Web"],
We want spaces in between our array entries, so like this here...and then on any others.

```suggestion
    "mediums": ["Audio", "Web"],
```

2024-03-14 16:52 UTC, bryanjnelson approved these changes
Thanks @willdch!  LGTM!

@CarsonF?

2024-03-14 17:23 UTC, CarsonF commented
Let's put these in their own files. I don't want to try to find the actual logic here in the middle of thousands of lines.
Not to mention your two PRs conflict with each other since they are both modifying the same spot.

2024-03-19 18:16 UTC, CarsonF approved these changes

2024-03-19 18:16 UTC, merged